=== discourse-lab/Connective-Lex.info/Web app/xml/dimlex.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT dimlex (entry)+>
<!ATTLIST dimlex
  xmlns CDATA #FIXED ''>

<!ELEMENT entry (orths, ambiguity, focuspart, correlate?, synonyms?, non_conn_reading?, stts, syn+)>
<!ATTLIST entry
  xmlns CDATA #FIXED ''
  edit NMTOKEN #IMPLIED
  id ID #REQUIRED
  word CDATA #REQUIRED
  type CDATA #IMPLIED>

<!ELEMENT orths (orth+)>
<!ATTLIST orths
  xmlns CDATA #FIXED ''>
  
<!ELEMENT orth (part+)>
<!ATTLIST orth
  xmlns CDATA #FIXED ''
  canonical (0 | 1) #REQUIRED
  onr ID #REQUIRED
  type (cont | discont) #REQUIRED>
  
<!ELEMENT part (#PCDATA)>
<!ATTLIST part
  xmlns CDATA #FIXED ''
  type (single | phrasal) #REQUIRED>

<!ELEMENT ambiguity (non_conn, sem_ambiguity)>
<!ATTLIST ambiguity
  xmlns CDATA #FIXED ''>
  
<!ELEMENT non_conn (#PCDATA)>
<!ATTLIST non_conn
  xmlns CDATA #FIXED ''
  edit NMTOKEN #IMPLIED
  freq CDATA #IMPLIED
  anno_N CDATA #IMPLIED>

<!ELEMENT sem_ambiguity (#PCDATA)>
<!ATTLIST sem_ambiguity
  xmlns CDATA #FIXED ''
  edit NMTOKEN #IMPLIED>

<!ELEMENT focuspart (#PCDATA)>
<!ATTLIST focuspart
  xmlns CDATA #FIXED ''>

<!ELEMENT correlate ((is_correlate, has_correlate)?, correlatee?)>
<!ATTLIST correlate
  xmlns CDATA #FIXED ''>
  
<!ELEMENT is_correlate (#PCDATA)>
<!ATTLIST is_correlate
  xmlns CDATA #FIXED ''>

<!ELEMENT has_correlate (#PCDATA)>
<!ATTLIST has_correlate
  xmlns CDATA #FIXED ''>

<!ELEMENT correlatee (corr+)>
<!ATTLIST correlatee
  xmlns CDATA #FIXED ''>
  
<!ELEMENT corr (#PCDATA)>
<!ATTLIST corr
  xmlns CDATA #FIXED ''>
  
<!ELEMENT synonyms (synonym*)>
<!ATTLIST synonyms
  xmlns CDATA #FIXED ''>
  
<!ELEMENT synonym (#PCDATA)>
<!ATTLIST synonym
  xmlns CDATA #FIXED ''
  lexicon NMTOKEN #IMPLIED
  version CDATA #IMPLIED
  entry-id NMTOKEN #IMPLIED
  language CDATA #IMPLIED
  word CDATA #IMPLIED>

<!ELEMENT non_conn_reading (#PCDATA|example)*>
<!ATTLIST non_conn_reading
  xmlns CDATA #FIXED ''>

<!ELEMENT stts (example*)>
<!ATTLIST stts
  xmlns CDATA #FIXED ''>
  
<!ELEMENT example (#PCDATA)>
<!ATTLIST example
  xmlns CDATA #FIXED ''
  tfreq CDATA #IMPLIED
  type NMTOKEN #IMPLIED>

<!ELEMENT syn (cat, (integr | praep)?, ordering?, sem+)>
<!ATTLIST syn
  xmlns CDATA #FIXED ''>

<!ELEMENT cat (#PCDATA)>
<!ATTLIST cat
  xmlns CDATA #FIXED ''>
  
<!ELEMENT integr (#PCDATA)>
<!ATTLIST integr
  xmlns CDATA #FIXED ''
  edit NMTOKEN #IMPLIED>
  
<!ELEMENT praep (ante, post, circum, case+)>
<!ATTLIST praep
  xmlns CDATA #FIXED ''>
  
<!ELEMENT ante (#PCDATA)>
<!ATTLIST ante
  xmlns CDATA #FIXED ''
  edit NMTOKEN #IMPLIED>

<!ELEMENT post (#PCDATA)>
<!ATTLIST post
  xmlns CDATA #FIXED ''
  edit NMTOKEN #IMPLIED>
  
<!ELEMENT circum (#PCDATA)>
<!ATTLIST circum
  xmlns CDATA #FIXED ''>
  
<!ELEMENT case (#PCDATA)>
<!ATTLIST case
  xmlns CDATA #FIXED ''
  edit NMTOKEN #IMPLIED>
  
<!ELEMENT ordering (ante?, post?, insert?, desintegr?)>
<!ATTLIST ordering
  xmlns CDATA #FIXED ''
  edit NMTOKEN #IMPLIED>
  
<!ELEMENT insert (#PCDATA)>
<!ATTLIST insert
  xmlns CDATA #FIXED ''>
  
<!ELEMENT desintegr (#PCDATA)>
<!ATTLIST desintegr
  xmlns CDATA #FIXED ''>
  
<!ELEMENT sem (pdtb3_relation*, pdtb2_relation*, sdrt_relation*, example*, synonyms?)>
<!ATTLIST sem
  xmlns CDATA #FIXED ''
  edit NMTOKEN #IMPLIED>

<!ELEMENT pdtb3_relation EMPTY>
<!ATTLIST pdtb3_relation
  xmlns CDATA #FIXED ''
  sense CDATA #REQUIRED
  freq CDATA #IMPLIED
  anno_N CDATA #IMPLIED>

<!ELEMENT pdtb2_relation EMPTY>
<!ATTLIST pdtb2_relation
  xmlns CDATA #FIXED ''
  sense CDATA #REQUIRED
  freq CDATA #IMPLIED
  anno_N CDATA #IMPLIED>
  
<!ELEMENT sdrt_relation EMPTY>
<!ATTLIST sdrt_relation
  xmlns CDATA #FIXED ''
  sense CDATA #REQUIRED
  type (sub | coord | unknown) #REQUIRED>

=== discourse-lab/Connective-Lex.info/Web app/xml/lico_d.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dimlex
  SYSTEM "dimlex.dtd">
<dimlex>
   <entry id="c1" word="a causa di">
      <orths>
         <orth type="cont" canonical="1" onr="c1o1">
            <part type="phrasal">a causa di</part>
         </orth>
         <orth type="cont" canonical="0" onr="c1o2">
            <part type="phrasal">A causa di</part>
         </orth>
      </orths>
      <ambiguity>
         <non_conn/>
         <sem_ambiguity/>
      </ambiguity>
      <focuspart/>
      <correlate/>
      <synonyms>
         <synonym lexicon="dimlex" entry-id="k19">aufgrund</synonym>
         <synonym lexicon="dimlex" entry-id="k21">aufgrund dessen, dass</synonym>
         <synonym lexicon="dimlex" entry-id="k160">wegen</synonym>
      </synonyms>
      <non_conn_reading/>
      <stts/>
      <syn>
         <cat>prepositional</cat>
         <integr/>
         <ordering/>
         <sem>
            <pdtb3_relation sense="CONTINGENCY:Cause:reason"/>
            <example>A causa del maltempo il St. Gotthard è rimasto chiuso.</example>
            <example>Una chiusura a causa del maltempo verrà presa in considerazione.</example>
         </sem>
      </syn>
   </entry>
   <entry id="c2" word="a condizione che">
      <orths>
         <orth type="cont" canonical="1" onr="c2o1">
            <part type="phrasal">a condizione che</part>
         </orth>
         <orth type="cont" canonical="0" onr="c2o2">
            <part type="phrasal">A condizione che</part>
         </orth>
      </orths>
      <ambiguity>
         <non_conn/>
         <sem_ambiguity/>
      </ambiguity>
      <focuspart/>
      <correlate/>
      <synonyms>
         <synonym lexicon="dimlex" entry-id="k133">sofern</synonym>
      </synonyms>
      <non_conn_reading/>
      <stts/>
      <syn>
         <cat>subordinating</cat>
         <integr/>
         <ordering/>
         <sem>
            <pdtb3_relation sense="CONTINGENCY:Condition"/>
            <example>Oggi usciamo, a condizione che venga Hans.</example>
            <example>Vuole restare all'istituto a condizione che ottenga il posto di assistente.</example>
         </sem>
      </syn>
   </entry>
   <entry id="c3" word="a dire il vero">
      <orths>
         <orth type="cont" canonical="1" onr="c3o1">
            <part type="phrasal">a dire il vero</part>
         </orth>
         <orth type="cont" canonical="0" onr="c3o2">
            <part type="phrasal">A dire il vero</part>
         </orth>
      </orths>
      <ambiguity>
         <non_conn/>
         <sem_ambiguity/>
      </ambiguity>
      <focuspart/>
      <correlate/>
      <synonyms>
         <synonym lexicon="dimlex" entry-id="k5">allerdings</synonym>
      </synonyms>
      <non_conn_reading/>
      <stts/>
      <syn>
         <cat>adverbial</cat>
         <integr/>
         <ordering/>
         <sem>
            <pdtb3_relation sense="COMPARISON:Concession:Arg2-as-denier"/>
            <example/>
         </sem>
      </syn>
   </entry>
   <entry id="c4" word="a dire la verità">
      <orths>
         <orth type="cont" canonical="1" onr="c4o1">
            <part type="phrasal">a dire la verità</part>
         </orth>
         <orth type="cont" canonical="0" onr="c4o2">
            <part type="phrasal">A dire la verità</part>
         </orth>
         <orth type="cont" canonical="0" onr="c4o3">
            <part type="phrasal">in verità</part>
         </orth>
         <orth type="cont" canonical="0" onr="c4o4">
            <part type="phrasal">In verità</part>
         </orth>
         <orth type="cont" canonical="0" onr="c4o5">
            <part type="phrasal">per la verità</part>
         </orth>
         <orth type="cont" canonical="0" onr="c4o6">
            <part type="phrasal">Per la verità</part>
         </orth>
      </orths>
      <ambiguity>
         <non_conn/>
         <sem_ambiguity/>
      </ambiguity>
      <focuspart/>
      <correlate/>
      <synonyms/>
      <non_conn_reading/>
      <stts/>
      <syn>
         <cat>adverbial</cat>
         <integr/>
         <ordering/>
         <sem>
            <pdtb3_relation sense="COMPARISON:Concession:Arg2-as-denier"/>
            <example/>
         </sem>
      </syn>
   </entry>
   <entry id="c5" word="a dispetto di">
      <orths>
         <orth type="cont" canonical="1" onr="c5o1">
            <part type="phrasal">a dispetto di</part>
         </orth>
         <orth type="cont" canonical="0" onr="c5o2">
            <part type="phrasal">A dispetto di</part>
         </orth>
      </orths>
      <ambiguity>
         <non_conn/>
         <sem_ambiguity/>
      </ambiguity>
      <focuspart/>
      <correlate/>
      <synonyms>
         <synonym lexicon="dimlex" entry-id="k142">trotz</synonym>
      </synonyms>
      <non_conn_reading/>
      <stts/>
      <syn>
         <cat>subordinating</cat>
         <integr/>
         <ordering/>
         <sem>
            <pdtb3_relation sense="COMPARISON:Concession:Arg1-as-denier"/>
            <example>Ci andiamo a dispetto del maltempo.</example>
            <example>Una seconda Pantherin ha lavorato fino al 67 anno di età, per acquisire, a dispetto della bassa paga oraria, una pensione.</example>
            <example>A dispetto del gran caldo estivo, il riscaldamento va a pieno regime.</example>
         </sem>
      </syn>
   </entry>
   <entry id="c6" word="a meno che">
      <orths>
         <orth type="cont" canonical="1" onr="c6o1">
            <part type="phrasal">a meno che</part>
         </orth>
         <orth type="cont" canonical="0" onr="c6o2">
            <part type="phrasal">A meno che</part>
         </orth>
         <orth type="cont" canonical="0" onr="c6o3">
            <part type="phrasal">a meno di</part>
         </orth>
         <orth type="cont" canonical="0" onr="c6o4">
            <part type="phrasal">A meno di</part>
         </orth>
      </orths>
      <ambiguity>
         <non_conn/>
         <sem_ambiguity/>
      </ambiguity>
      <focuspart/>
      <correlate/>
      <synonyms>
         <synonym lexicon="dimlex" entry-id="k24">außer</synonym>
         <synonym lexicon="dimlex" entry-id="k133">sofern</synonym>
      </synonyms>
      <non_conn_reading/>
      <stts/>
      <syn>
         <cat>subordinating</cat>
         <integr/>
         <ordering/>
         <sem>
            <pdtb3_relation sense="CONTINGENCY:Negative-Condition:Arg2-as-negcond"/>
            <example>In caso di divorzio la madre ottiene l'affidamento dei minori, a meno che il giudice non decida altrimenti.</example>
            <example>Domani vado in montagna, a meno che il tempo non faccia brutti scherzi.</example>
            <example>Oggi usciamo, a meno che Hans venga.</example>
            <example>Vuole restare all'istituto, a meno che non ottenga il posto di assistente.</example>
            <example>A meno che tu non abbia niente di meglio in programma, vieni al cinema domani?</example>
         </sem>
      </syn>
   </entry>
   <entry id="c7" word="a onor del vero">
      <orths>
         <orth type="cont" canonical="1" onr="c7o1">
            <part type="phrasal">a onor del vero</part>
         </orth>
         <orth type="cont" canonical="0" onr="c7o2">
            <part type="phrasal">A onor del vero</part>
         </orth>
      </orths>
      <ambiguity>
         <non_conn/>
         <sem_ambiguity/>
      </ambiguity>
      <focuspart/>
      <correlate/>
      <synonyms/>
      <non_conn_reading/>
      <stts/>
      <syn>
         <cat>adverbial</cat>
         <integr/>
         <ordering/>
         <sem>
            <pdtb3_relation sense="COMPARISON:Concession:Arg2-as-denier"/>
            <example/>
         </sem>
      </syn>
   </entry>
   <entry id="c8" word="a tal fine">
      <orths>
         <orth type="cont" canonical="1" onr="c8o1">
            <part type="phrasal">a tal fine</part>
         </orth>
         <orth type="cont" canonical="0" onr="c8o2">
            <part type="phrasal">A tal fine</part>
         </orth>
      </orths>
      <ambiguity>
         <non_conn/>
         <sem_ambiguity/>
      </ambiguity>
      <focuspart/>
      <correlate/>
      <synonyms>
         <synonym lexicon="dimlex" entry-id="k35">dafür</synonym>
      </synonyms>
      <non_conn_reading/>
      <stts/>
      <syn>
         <cat>coodinating</cat>
         <integr/>
         <ordering/>
         <sem>
            <pdtb3_relation sense="CONTINGENCY:Purpose:Arg1-as-goal"/>
            <example/>
         </sem>
      </syn>
   </entry>
   <entry id="c9" word="ad esempio">
      <orths>
         <orth type="cont" canonical="1" onr="c9o1">
            <part type="phrasal">ad esempio</part>
         </orth>
         <orth type="cont" canonical="0" onr="c9o2">
            <part type="phrasal">Ad esempio</part>
         </orth>
         <orth type="cont" canonical="0" onr="c9o3">
            <part type="phrasal">per esempio</part>
         </orth>
         <orth type="cont" canonical="0" onr="c9o4">
            <part type="phrasal">Per esempio</part>
         </orth>
      </orths>
      <ambiguity>
         <non_conn/>
         <sem_ambiguity/>
      </ambiguity>
      <focuspart/>
      <correlate/>
      <synonyms/>
      <non_conn_reading/>
      <stts/>
      <syn>
         <cat>coodinating</cat>
         <integr/>
         <ordering/>
         <sem>
            <pdtb3_relation sense="EXPANSION:Instantiation"/>
            <example/>
         </sem>
      </syn>
   </entry>
   <entry id="c10" word="ad ogni modo">
      <orths>
         <orth type="cont" canonical="1" onr="c10o1">
            <part type="phrasal">ad ogni modo</part>
         </orth>
